# Generated by Django 4.2.6 on 2023-10-10 21:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exames', '0004_rename_pedidosexames_pedidosexame_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedidosExame',
            new_name='PedidosExames',
        ),
        migrations.RenameModel(
            old_name='TiposExame',
            new_name='TiposExames',
        ),
    ]
